### ISSUE TITLE
Https by default for Thyra pages not working

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#498] opened 2023-03-01 09:41 UTC
**The problem(s)**
Thyra's home page and plugin-manager pages aren't in HTTPS by default. 

**To Reproduce**
1. Use case 1: 
* Go to my.massa/thyra/home/ 
* It opens http://my.massa/thyra/home  --> it should open https://my.massa/thyra/home/ by default 
* 
2. Use case 2:
* Go to https://my.massa/thyra/home/ 
* It opens http://my.massa/thyra/home/ 
* Add again https:// at the beginning of the address, it opens secure page. --> it should work the first time.

**Expected behavior(s)**
Https should be by default for all Thyra's pages.

**Screenshots**
See video: https://drive.google.com/file/d/19CrASaa8f3Hc4pQliiT_V67YIfqaZR-r/view?usp=share_link

**Thyra version**
latest as of today

**Desktop (please complete the following information):**
 - OS: MacOS
 - Google Chrome

**Comment by 0xMazout** [comment] 2023-03-01 10:15
The problem comes from the interceptor in the thyra backend. 

I created a ticket about this but it was closed.

We have an interceptor in the thyra backend. each website composed by my.massa will be prefixed with http. we need to change it to https

**Comment by SlnPons** [comment] 2023-03-06 14:42
@0xMazout could you add some link to the doc about this "interceptor" please? 
If the run team works on it, it will be hard for them to get into the problem. Also is it specific to MacOS?

**Comment by 0xMazout** [comment] 2023-03-06 14:57
> @0xMazout could you add some link to the doc about this "interceptor" please? If the run team works on it, it will be hard for them to get into the problem. Also is it specific to MacOS?

Yes no problem i was looking for some info on it.

**Comment by 0xMazout** [comment] 2023-03-06 15:13
No it's not specific to MacOS it's related to all websites which include my.massa in their url.

In the Thyra Backend we have interceptors, to redirect on the right routes and to have format in urls. 
The sum of this interceptors give an http redirect. 

You need to isolate the specific interceptors and change it to have an https instead of an http. 

Actually i don't know what is the good interceptor.

What i can give to you is the route 
![image](https://user-images.githubusercontent.com/10938862/223150886-08621159-4aec-4e5c-b549-5239aaeff320.png)

And potential files to search 
![image](https://user-images.githubusercontent.com/10938862/223150515-a4fb1674-3b38-4707-8071-c6df03d99a87.png)


I don't have a clear solution but i think this will help you in your search

**Comment by SlnPons** [comment] 2023-03-07 08:01
Thanks a lot @0xMazout
@thomas-senechal can you check the details added by 0xMazout and tell us if it's clearer please? 
If it rings a bell on your side, let's do it with the run team. If not, we'll keep it as it's quite important and urgent ;) 
Cheers

**Comment by thomas-senechal** [comment] 2023-03-07 14:32
I made some researches about it and here is what I found. 

Every requests goes in [`RedirectToDefaultResourceInterceptor`](https://github.com/massalabs/thyra/blob/175675363fa97e1fc706288dff347a1b18e0c7ab/pkg/onchain/website/handler.go#L49)

In this function, modifying [this line](https://github.com/massalabs/thyra/blob/175675363fa97e1fc706288dff347a1b18e0c7ab/pkg/onchain/website/handler.go#L66) adding an `s` for `https` fixes the issue in some cases:
- `my.massa/thyra/wallet/` -> https
- `my.massa/thyra/wallet/index.html` -> http
- `http://my.massa/thyra/wallet/` -> https
- `http://my.massa/thyra/wallet/index.html` -> http
- `https://my.massa/thyra/wallet/` -> https
- `https://my.massa/thyra/wallet/index.html` -> https

As you can see, if the protocol (`http` or `https`) isn't specified, the request will be redirected to `http` or `https` depending on if the request contains something after `wallet` or not. We can see the same behavior with `http`.

This behavior is due to [this `if`](https://github.com/massalabs/thyra/blob/175675363fa97e1fc706288dff347a1b18e0c7ab/pkg/onchain/website/handler.go#L63). I think we should find a way to modify it to avoid basing `http`/`https` handling on the number of routes in the Request' URL Path.

I think we could use `req.Request.TLS` to check if the request is an http or https request.

**Comment by thomas-senechal** [comment] 2023-03-07 22:41
@SlnPons Hey !
I couldn't reproduce the exact wanted behavior without redirecting every requests to `https`. 
My implementation will always keep the asked protocol, and so, give a result as follow:
- `http://my.massa/thyra/wallet/` -> http
- `http://my.massa/thyra/wallet/index.html` -> http
- `https://my.massa/thyra/wallet/` -> https
- `https://my.massa/thyra/wallet/index.html` -> https

If the protocol isn't specified in the URL (so for example `my.massa/thyra/wallet/` and `my.massa/thyra/wallet/index.html`), the result is kinda random. It depends on multiple things such as the WebBrowser, the cache, the user WebBrowser settings... So sometimes, a URL starting without the protocol will be redirected by the WebBrowser to `https`, and sometime it will be redirected as `http`. 

If we want, we can force to use `https`, but I'm not sure it's really useful since users will be redirected to their own computer and so, I don't think they can be attacked. 

Please tell me if you want me to change the behavior to redirecting every requests to `https`, or if we should merge my PR as it is, with the behavior described in this comment.

**Comment by SlnPons** [comment] 2023-03-08 11:42
Massa web on-chain should match the default behaviour of standard web if we want to reach mass-adoption. So I would say that all the pages should be `https` be default. 
@gregLibert what do you think?

**Comment by gregLibert** [comment] 2023-03-08 16:49
I think the wallet will be removed from Thyra soon. So I don't want to spend too much time on it.

However, the question remains for :
- XXX.massa => in this case, I think the browser tries to access https://XXX.massa first and falls back to http://XXX.massa. But since the HTTPS version works in most cases (FF on Windows being the exception) this case is covered.
- thyra/plugin/<author>/<plugin>/... => this is driven by the frontend application. if we use HTTPS, https must be used. So this case is also covered.

Am I missing something?

**Comment by thomas-senechal** [comment] 2023-03-09 08:24
> * XXX.massa => in this case, I think the browser tries to access https://XXX.massa first and falls back to http://XXX.massa. But since the HTTPS version works in most cases (FF on Windows being the exception) this case is covered.

It depends on the browser. For example, Safari and Firefox doesn't accept `my.massa` (or any `.massa` website) and will redirected to a search for the asked `.massa` website. But on my webbrowser, Brave (Chromium under the hood), typing `my.massa` redirect me to the http version. Same for any other `.massa` website such as `flappy.massa`.

AFAIK, the behavior for URLs without a specified protocol entirely depends on the WebBrowser. It can be changed depending on the WebBrowser settings, it's cache....

**Comment by SlnPons** [comment] 2023-03-09 09:18
My issue is not about the wallet. Thyra manages 2 kind of pages: 
1.  *.massa
2. my.massa/thyra/* 

The discussion here concerns both these cases. Please @thomas-senechal think about the project globally and not in terms of pages only otherwise we'll go in circle ;)

So my question is: 
--> should the default behaviour for thyra's pages always be: open everything in `https` OR 
--> should the default behaviour be the default behaviour of the web browser used (ie: random based on cache and all sorts of settings...) 

I do believe that current web standards is `https` by default. So I would say same behaviour for thyra. But I'm not sure it's relevant to force this. What do you think @gregLibert

**Comment by Thykof** [comment] 2023-03-09 09:43
Sorry I merged the PR too fast, so I reverted it, the I reopen this issue

**Comment by gregLibert** [comment] 2023-03-09 13:56
@SlnPons my point is that the end user only use the first kind of page (*.massa). The second kind (my.massa/thyra/*) is only use by another application (front, back of a plugin...).
If we only consider the first kind, all calls work using https, except for FF on windows.

**Comment by SlnPons** [comment] 2023-03-09 16:47
`*.massa: all calls work using https, except for FF on windows.` - yes, ok that's the rule we should implement. 

About the my.massa/thyra/* , i'm not sure to follow your reflexion :/. Because based on the current user flow all thyra users will access my.massa/thyra/home (at the very least one time). 
Then all plugins will have an URL like this: my.massa/thyra/authorName/pluginName so again a my.massa/* 
Do I misunderstand sth here?

**Comment by SlnPons** [comment] 2023-03-10 10:08
@thomas-senechal I synced wth Greg because we struggled to understand each other 😅 sorry about that. 
In conclusion: 
- all *.massa should be in https by default. Which means that: As a user if I type flappy.massa on my search bar I am automatically redirected to: https://flappy.massa. 
--> As Greg was saying it's the only URL that people will need to type manually. 

- other URLs like my.massa/thyra/* don't have to be forced to https strictly speaking. It as best as it's web standard but: 
1. It's localhost to very low risk for it not to be https.
2. As a user I will access these pages via Thyra app and so I probably won't have to type them. --> so we have to make sure we always use `https://my.massa/thyra/*` on thyra app redirection.

I hope it's clearer for you! :)

**Closed** 2023-03-17 13:59 UTC
Labels: issue:bug
