### ISSUE TITLE
Get stuck on password prompt

### ISSUE THREAD

**Issue by qdrn** [massalabs/thyra#401] opened 2023-01-11 11:04 UTC
**Describe the bug**
Sometimes when trying to upload a website, Thyra gets stuck on the password prompt: I enter my password and confirm and the password prompt doesn't disappear and can't be interacted with anymore.

**Thyra version**
latest

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by SlnPons** [comment] 2023-01-12 18:12
@thomas-senechal I remember experiencing the same bug when we were working on thyra together and you told me it was due to sth in particular. Would you be able to remind me what it was? 
(we solved it by simply turning thyra off and on again) 
Cheers

**Comment by SlnPons** [comment] 2023-03-06 14:02
Can't reproduce this issue, and no other users reported the same problem so I will close this issue for now :)

**Closed by SlnPons** 2023-03-06 14:02 UTC
Labels: issue:bug
