### ISSUE TITLE
BUG - deploying webstorage SC: deployment time is out

### ISSUE THREAD

**Issue by gregLibert** [massalabs/thyra#252] opened 2022-11-11 07:00 UTC
# What I did
- Checkout branch 218-deploy-thyra-on-innonet-15
- Try to deploy a website using the https://my.massa/thyra/websiteCreator/index.html page

# Problem encountered number 1
Nothing heppens except a super annoying error: "Error while looking for your domain names" (related to a Domains-0001)

# Identification of the root cause
1-  [here](https://github.com/massalabs/thyra/blob/218-deploy-thyra-on-innonet-15/pkg/onchain/sc.go#L43) we ask the end user to wait 3 minutes (45*2*2s = 180s)
 2- finally, when the error is triggered, it is immediately covered by a new "Error while looking for your domain names"  error

# Problem encountered number 2
The call to the deployer SC does not work. But this is maybe linked to the unfinished work of this PR.

**Comment by SlnPons** [comment] 2022-11-30 09:23
Can't reproduce this error so I'll close it. 
Assumption: 
* It was due to the fact that the wallet was empty. No coin = can't deploy => you wait for nothing until the expiry date.
* You try multiple times to deploy a website (eg: you refresh the page after clicking on deploy, ...). In that case, the event manager sends all events received from previous operations as soon as you come back to the websites page thus the errors you saw. 

But I'm 99% sure it's due to the wallet being empty.

**Closed by SlnPons** 2022-11-30 09:23 UTC
