### ISSUE TITLE
Error of Failed requests: BadShmSeg

### ISSUE THREAD

**Issue by altai0** [massalabs/thyra#499] opened 2023-03-01 12:21 UTC
**The problem(s)**
I got this error when trying to load or create a wallet and thyra-server stopped working. Also when I try to go to the node manager plugin page the page gives an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/36895904/222137138-16871518-8aea-49eb-bc65-919b6c491d29.png)
![image](https://user-images.githubusercontent.com/36895904/222137899-6c4b81f6-7f92-4ad1-952c-3e40ac47ef1c.png)

**Thyra version**
0.1.10

**Desktop :**
 - OS: Ubuntu 22
 **Any other useful info**

**Comment by SlnPons** [comment] 2023-03-06 15:29
Hey @altai0 thanks for reporting this issue. 
I do believe that you were trying to use thyra on testnet20 ... however thyra is still not available on this testnet :/ 
The error messaging is still not clear so it's hard for me to be sure that this is what you were trying to do. Could you confirm that you ran thyra on testnet20?

**Comment by SlnPons** [comment] 2023-03-27 18:24
Couldn't reproduce this issue. Please feel free to re-open it and ping me if you still experiencing this problem. 
As for now, I'll close it :)

**Closed by SlnPons** 2023-03-27 18:24 UTC
Labels: issue:bug
