### ISSUE TITLE
Deploy a website on testnet20 using thyra - KO

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra#517] opened 2023-03-08 18:01 UTC
**The problem(s)**
When trying to deploy a website using thyra on testnet20, I've got an error. See screenshot below

**To Reproduce**

1. Go on thyra latest main version 
2. Try to upload flappy with a wallet with tokens 
3. Get the error on your console

**Expected behavior(s)**
Flappy is uploaded on the blockchain

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/109611779/223792916-40c4f235-ff44-45c3-82c3-a50d1c65fe4b.png">

**Thyra version**
Thyra latest main branch version at 7pm on 8/03/23

**Comment by thomas-senechal** [comment] 2023-03-13 08:42
The DNS address in the screenshot is the one of the Testnet 19. It has been updated for Testnet 20 in [this commit](https://github.com/massalabs/thyra/commit/ba3088ae4a2aff4fdc973d7d2086bc7eaa3f644b)
Updating Thyra should fix the issue 

I'm closing the issue, feel free to reopen it if the issue is still there after the update ! :)

**Closed by thomas-senechal** 2023-03-13 08:42 UTC
Labels: issue:bug, P1
