### ISSUE TITLE
thyra app launch a non responsive button after installation 

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/thyra#523] opened 2023-03-10 09:48 UTC
**The problem(s)**
the installation of thyra creates a thyra-app icon that seems to be from an older version and does not respond 

**To Reproduce**

run `sudo ./thyra-installer_linux_amd64`
right click on the icon

**Expected behavior(s)**
normal installation 
**Screenshots**
![image](https://user-images.githubusercontent.com/83134981/224281852-0b530bf7-6e42-4eb1-a39d-0d013f971362.png)

**Thyra version**
0.1.10

**Desktop (please complete the following information):**
ubuntu 22
 
 **Any other useful info**

**Comment by SlnPons** [comment] 2023-03-13 13:42
@Pierregvx could you test with the installer available on the latest release to see if you still have this problem please? 
https://github.com/massalabs/thyra/releases/tag/v0.1.11

Let me know

**Comment by Pierregvx** [comment] 2023-03-13 15:38
still there @SlnPons

**Comment by SlnPons** [comment] 2023-03-13 17:38
fyi - @thomas-senechal 
It seems that Linux installer has a problem as reported by Pierre. 
2 potential root causes to deep dive
* Thyra app release is outdated / the installer code is not using the latest one - because I do remember doing a release after the latest changes .... to be checked in the code 
* Thyra installer on Linux hasn't been tested correctly after: https://github.com/massalabs/thyra/issues/449 

Let me know if I can help :)

**Comment by thomas-senechal** [comment] 2023-03-13 18:33
Couldn't reproduce with a VM running Ubuntu 22.04 freshly installed.

And couldn't reproduce on my laptop running Ubuntu 22.10 due to this issue https://github.com/massalabs/Thyra-Menu-Bar-App/issues/43

@Pierregvx , could you give me the precise version of your Ubuntu ?

**Comment by thomas-senechal** [comment] 2023-03-13 18:36
> * Thyra app release is outdated / the installer code is not using the latest one - because I do remember doing a release after the latest changes .... to be checked in the code

You are right, the latest version has been made after the latest changes.

> * Thyra installer on Linux hasn't been tested correctly after: [Use the Python installer for Linux installation #449](https://github.com/massalabs/thyra/issues/449)

Following [my previous comment](https://github.com/massalabs/thyra/issues/523#issuecomment-1466711435), I don't think it's necessarly an issue due to tests, but more to an issue of different versions of Linux. We will need to investigate those issues.

**Comment by Pierregvx** [comment] 2023-03-14 06:13
I have my vm on ubuntu 22.04. Perhaps I didn't do my snapshot correctly, I'll check

**Comment by thomas-senechal** [comment] 2023-03-14 07:43
@Pierregvx Don't you have anything in particular in your terminal after starting Thyra App ? Any warning or error ?

Seeing my issue on my laptop running Ubuntu 22.10, and yours on Ubuntu 22.04, I'm thinking it might be related to a dependency that we need to install while installing Thyra App.

**Comment by Pierregvx** [comment] 2023-03-14 09:46
I don't have any problem when I run thyra-app it is just after the installation

**Comment by thomas-senechal** [comment] 2023-03-14 14:48
We made a call with @Pierregvx to investigate and found the issue. 

Users shouldn't start the installer using `sudo`. If they do, the installer will create `.config/thyra` in the `root` `$HOME` directory which wont allow Thyra to be started using Thyra App or command lines. Also, Thyra App will also be started as `root` (understand here, with `sudo`) at the end of the installation. And so, when the user clicks on the `Wallet` or `Web OnChain` button, the webpage cannot be opened because the user isn't the `root` user. 

A simple fix to that is to tell users to not start the installer with `sudo`. The issue with that "fix" is that users might still use `sudo` if they didnt read the [`INSTALLATION.md`](https://github.com/massalabs/thyra/blob/7405055e215b1f4242f5e700fd02134a49c85cec/INSTALLATION.md) file correctly. 
And so, I think we should add a check at the beginning of the installation to tell the user that they are running the script as `sudo` and that it should only be done if they are using the `root` user. We could then add a question to ask the user if they want to continue the installation as root or stop so they can restart the installer without `sudo`.

**Comment by SlnPons** [comment] 2023-03-14 18:07
@thomas-senechal, @Pierregvx I'm struggling to understand if this is a problem tbh. 
The installer is made for non-dev users so users will never do a `sudo` to install thrya, they don't know what it is. 
Why would you need to do a `sudo` to install thyra? 
The user-flow is: Download the installer > the file is executable, so you click on it > thyra is installed. 
Where does the sudo comes in the flow for a dev user?

**Comment by thomas-senechal** [comment] 2023-03-14 18:25
> The installer is made for non-dev users so users will never do a `sudo` to install thrya, they don't know what it is. Why would you need to do a `sudo` to install thyra? The user-flow is: Download the installer > the file is executable, so you click on it > thyra is installed. Where does the sudo comes in the flow for a dev user?

You are right. It's just that some people are used to use `sudo` when installing stuff (which is a bad practice IMO). 
Now that we know some people might make the mistake, I think we should make sure it won't happen again. 
But this isn't a priority IMHO. 

Maybe we should add this issue to the Run board as a low priority ? So we keep track of this bug to tackle it later.

**Comment by gregLibert** [comment] 2023-03-14 18:37
This also means that thyra install is not multi user...

@thomas-senechal Could we do the opposite and create `.config/thyra` if it doesn't exist when thyra start?

**Comment by thomas-senechal** [comment] 2023-03-14 18:39
> Could we do the opposite and create `.config/thyra` if it doesn't exist when thyra start?

That's clearly a better idea. Will make sure to do it for the `plugins` and `certs` directories if it's not already done.

**Comment by SlnPons** [comment] 2023-03-15 08:10
Thank you guys! Let's go with the solution you suggested @gregLibert and thanks @thomas-senechal for including plugins and certs :)

**Closed** 2023-03-27 07:43 UTC
Labels: issue:bug
